version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master_001_sdaoijasdk
    restart: always
    environment:
      CRAWLAB_NODE_MASTER: "Y"  # Y: master node
      CRAWLAB_MONGO_HOST: "mongo_service_001_89_29_39"  # mongo host address. In the docker compose network, directly refer to the service name
      CRAWLAB_MONGO_PORT: "27017"  # mongo port 
      CRAWLAB_MONGO_DB: "crawlab"  # mongo database 
      CRAWLAB_MONGO_USERNAME: "carawlab_mongo_user_8956466"  # mongo username
      CRAWLAB_MONGO_PASSWORD: "1B95454cDsds$dsDw33_eS"  # mongo password 
      CRAWLAB_MONGO_AUTHSOURCE: "admin"  # mongo auth source 
    # volumes:
    #   - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
    #   - "/opt/crawlab/master:/data"  # persistent crawlab data
    #   - "/var/crawlab/log:/var/log/crawlab" # log persistent 
    ports:
      - "8080:8080"  # exposed api port
    depends_on:
      - mongo_service_001_89_29_39

  mongo_service_001_89_29_39:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "carawlab_mongo_user_8956466"  # mongo username
      MONGO_INITDB_ROOT_PASSWORD: "1B95454cDsds$dsDw33_eS"  # mongo password
    # volumes:
    #   - "/opt/.crawlab/master:/root/.crawlab"  # persistent crawlab metadata
    #   - "/opt/crawlab/mongo/data/db:/data/db"  # persistent mongo data
    ports:
      - "27017:27017"  # expose mongo port to host machine
